version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    env_file:
      - .env.local
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
